/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'eventId' : bigint,
  'confirmationCode' : string,
  'tierId' : bigint,
  'attendeeName' : string,
  'attendeeEmail' : string,
  'createdAt' : bigint,
  'attendeePhone' : string,
  'quantity' : bigint,
  'totalPrice' : number,
}
export interface EventPublic {
  'id' : bigint,
  'title' : string,
  'venue' : string,
  'city' : string,
  'date' : bigint,
  'description' : string,
  'imageUrl' : string,
  'availableSeats' : bigint,
  'category' : string,
  'rating' : number,
  'capacity' : bigint,
  'price' : number,
  'reviewCount' : bigint,
  'location' : string,
}
export type Result = { 'ok' : Booking } |
  { 'err' : string };
export interface Review {
  'id' : bigint,
  'eventId' : bigint,
  'date' : bigint,
  'authorName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface TicketTierPublic {
  'id' : bigint,
  'eventId' : bigint,
  'total' : bigint,
  'name' : string,
  'available' : bigint,
  'benefits' : Array<string>,
  'price' : number,
}
export interface _SERVICE {
  'addReview' : ActorMethod<[bigint, string, bigint, string], Review>,
  'createBooking' : ActorMethod<
    [bigint, bigint, bigint, string, string, string],
    Result
  >,
  'getEvent' : ActorMethod<[bigint], [] | [EventPublic]>,
  'getEvents' : ActorMethod<[], Array<EventPublic>>,
  'getEventsByCategory' : ActorMethod<[string], Array<EventPublic>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getTicketTiers' : ActorMethod<[bigint], Array<TicketTierPublic>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];