/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'date' : IDL.Int,
  'authorName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Nat,
  'confirmationCode' : IDL.Text,
  'tierId' : IDL.Nat,
  'attendeeName' : IDL.Text,
  'attendeeEmail' : IDL.Text,
  'createdAt' : IDL.Int,
  'attendeePhone' : IDL.Text,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Float64,
});
export const Result = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
export const EventPublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'availableSeats' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'capacity' : IDL.Nat,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const TicketTierPublic = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'total' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Nat,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [Review], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(EventPublic)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(EventPublic)], ['query']),
  'getEventsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EventPublic)],
      ['query'],
    ),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getTicketTiers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TicketTierPublic)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'date' : IDL.Int,
    'authorName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Nat,
    'confirmationCode' : IDL.Text,
    'tierId' : IDL.Nat,
    'attendeeName' : IDL.Text,
    'attendeeEmail' : IDL.Text,
    'createdAt' : IDL.Int,
    'attendeePhone' : IDL.Text,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Float64,
  });
  const Result = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  const EventPublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'availableSeats' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'capacity' : IDL.Nat,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const TicketTierPublic = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'total' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Nat,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [Review],
        [],
      ),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(EventPublic)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(EventPublic)], ['query']),
    'getEventsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EventPublic)],
        ['query'],
      ),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getTicketTiers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TicketTierPublic)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };